export const achievements = [
  {
    id: 0,
    title: "steadySteps",
    description: "consecutiveLogins",
    locked: true,
    lockedImage: "/assets/images/passos-constantes-locked.svg",
    unlockedImage: "/assets/images/passos-constantes-unlocked.svg",
  },
  {
    id: 1,
    title: "mastersRhythm",
    description: "stayActive",
    locked: true,
    lockedImage: "/assets/images/ritmo-de-mestre-locked.svg",
    unlockedImage: "/assets/images/ritmo-de-mestre-unlocked.svg",
  },
  {
    id: 2,
    title: "unwaveringCommitment",
    description: "stayActive",
    locked: true,
    lockedImage: "/assets/images/compromisso-inabalavel-locked.svg",
    unlockedImage: "/assets/images/compromisso-inabalavel-unlocked.svg",
  },
  {
    id: 3,
    title: "goodGuess",
    description: "stayActive",
    locked: true,
    lockedImage: "/assets/images/bom-palpite-locked.svg",
    unlockedImage: "/assets/images/bom-palpite-unlocked.svg",
  },
  {
    id: 4,
    title: "quizAce",
    description: "answerQuestions",
    locked: true,
    lockedImage: "/assets/images/craque-do-quiz-locked.svg",
    unlockedImage: "/assets/images/craque-do-quiz-unlocked.svg",
  },
  {
    id: 5,
    title: "answerGenius",
    description: "answerQuestions",
    locked: true,
    lockedImage: "/assets/images/genio-das-respostas-locked.svg",
    unlockedImage: "/assets/images/genio-das-respostas-unlocked.svg",
  },
  {
    id: 6,
    title: "challengeExplorer",
    description: "answerQuestions",
    locked: true,
    lockedImage: "/assets/images/explorador-de-desafios-locked.svg",
    unlockedImage: "/assets/images/explorador-de-desafios-unlocked.svg",
  },
  {
    id: 7,
    title: "dedicatedCompetitor",
    description: "completeChallenges",
    locked: true,
    lockedImage: "/assets/images/competidor-dedicado-locked.svg",
    unlockedImage: "/assets/images/competidor-dedicado-unlocked.svg",
  },
  {
    id: 8,
    title: "masterOfChallenges",
    description: "completeChallenges",
    locked: true,
    lockedImage: "/assets/images/mestre-dos-desafios-locked.svg",
    unlockedImage: "/assets/images/mestre-dos-desafios-unlocked.svg",
  },
  {
    id: 9,
    title: "firstAchievement",
    description: "completeChallenges",
    locked: true,
    lockedImage: "/assets/images/primeira-conquista-locked.svg",
    unlockedImage: "/assets/images/primeira-conquista-unlocked.svg",
  },
  {
    id: 10,
    title: "perfeccionist",
    description: "firstOfMany",
    locked: true,
    lockedImage: "/assets/images/perfeccionista-locked.svg",
    unlockedImage: "/assets/images/perfeccionista-unlocked.svg",
  },
  {
    id: 11,
    title: "personality",
    description: "maxAccuracy",
    locked: true,
    lockedImage: "/assets/images/personalidade-locked.svg",
    unlockedImage: "/assets/images/personalidade-unlocked.svg",
  },
];
