export const achievements = [
  {
    id: 1,
    title: "Passos constantes",
    description: "Conquiste logins consecutivos e avance nos níveis de compromisso.",
    locked: false,
    lockedImage: "/assets/images/passos-constantes-locked.svg",
    unlockedImage: "/assets/images/passos-constantes-unlocked.svg",
  },
  {
    id: 2,
    title: "Ritmo de mestre",
    description: "Mantenha-se ativo e avance nos níveis de compromisso.",
    locked: true,
    lockedImage: "/assets/images/ritmo-de-mestre-locked.svg",
    unlockedImage: "/assets/images/ritmo-de-mestre-unlocked.svg",
  },
  {
    id: 3,
    title: "Compromisso inabalável",
    description: "Mantenha-se ativo e avance nos níveis de compromisso.",
    locked: true,
    lockedImage: "/assets/images/compromisso-inabalavel-locked.svg",
    unlockedImage: "/assets/images/compromisso-inabalavel-unlocked.svg",
  },
  {
    id: 4,
    title: "Bom palpite",
    description: "Mantenha-se ativo e avance nos níveis de compromisso.",
    locked: false,
    lockedImage: "/assets/images/bom-palpite-locked.svg",
    unlockedImage: "/assets/images/bom-palpite-unlocked.svg",
  },
  {
    id: 5,
    title: "Craque do Quiz",
    description: "Acerte perguntas e avance nos níveis do quiz.",
    locked: true,
    lockedImage: "/assets/images/craque-do-quiz-locked.svg",
    unlockedImage: "/assets/images/craque-do-quiz-unlocked.svg",
  },
  {
    id: 6,
    title: "Gênio das respostas",
    description: "Acerte perguntas e avance nos níveis do quiz.",
    locked: true,
    lockedImage: "/assets/images/genio-das-respostas-locked.svg",
    unlockedImage: "/assets/images/genio-das-respostas-unlocked.svg",
  },
  {
    id: 7,
    title: "Explorador de desafios",
    description: "Acerte perguntas e avance nos níveis do quiz.",
    locked: false,
    lockedImage: "/assets/images/explorador-de-desafios-locked.svg",
    unlockedImage: "/assets/images/explorador-de-desafios-unlocked.svg",
  },
  {
    id: 8,
    title: "Competidor dedicado",
    description: "Complete desafios para se tornar um mestre.",
    locked: false,
    lockedImage: "/assets/images/competidor-dedicado-locked.svg",
    unlockedImage: "/assets/images/competidor-dedicado-unlocked.svg",
  },
  {
    id: 9,
    title: "Mestre dos desafios",
    description: "Complete desafios para se tornar um mestre.",
    locked: false,
    lockedImage: "/assets/images/mestre-dos-desafios-locked.svg",
    unlockedImage: "/assets/images/mestre-dos-desafios-unlocked.svg",
  },
  {
    id: 10,
    title: "Primeira conquista",
    description: "Complete desafios para se tornar um mestre.",
    locked: false,
    lockedImage: "/assets/images/primeira-conquista-locked.svg",
    unlockedImage: "/assets/images/primeira-conquista-unlocked.svg",
  },
  {
    id: 4,
    title: "Perfeccionista",
    description: "A primeira de muitas conquistas.",
    locked: true,
    lockedImage: "/assets/images/perfeccionista-locked.svg",
    unlockedImage: "/assets/images/perfeccionista-unlocked.svg",
  },
  {
    id: 5,
    title: "Personalidade",
    description: "Atingiu 100% de precisão em uma tarefa.",
    locked: false,
    lockedImage: "/assets/images/personalidade-locked.svg",
    unlockedImage: "/assets/images/personalidade-unlocked.svg",
  },
];
