name: API CI/CD Workflow

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
    paths:
      - "packages/api/**"
      - ".github/workflows/api-ci-cd.yml"

permissions:
  id-token: write
  contents: read

concurrency:
  group: api-workflow-${{ github.ref }}
  cancel-in-progress: true

env:
  MONGODB_VERSION: 7.0.5-jammy
  MONGODB_HOST: localhost
  MONGODB_PORT: 27017
  MONGODB_DB: doteducation
  API_PORT: 4000
  HOST: 0.0.0.0

jobs:
  api-build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.base.ref || github.ref_name }}

    steps:
      - name: Create codebase directory
        run: mkdir -p codebase

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: codebase/api

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.29

      - name: Set up environment variables for API
        working-directory: codebase/api
        run: |
          touch .env
          echo "NODE_ENV=test" >> .env
          echo "HOST=${{ env.HOST }}" >> .env
          echo "PORT=${{ env.API_PORT }}" >> .env
          echo "MONGODB_URI=mongodb://${{ env.MONGODB_HOST }}:${{ env.MONGODB_PORT }}/${{ env.MONGODB_DB }}" >> .env

      - name: Install API dependencies
        working-directory: codebase/api
        run: bun i

      - name: Format
        working-directory: codebase/api
        run: bun run format

      - name: Lint
        working-directory: codebase/api
        run: bun run lint

      - name: Build
        working-directory: codebase/api
        run: bun run build

      - name: Create logs directory
        run: mkdir -p logs

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ env.MONGODB_VERSION }}
          mongodb-port: ${{ env.MONGODB_PORT }}
          mongodb-db: ${{ env.MONGODB_DB }}

      - name: Run API tests
        working-directory: codebase/api
        run: bun test

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: api-service-logs
          include-hidden-files: true
          path: logs
