name: App CI/CD Workflow

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
    paths:
      - "packages/app/**"
      - ".github/workflows/app-ci-cd.yml"

permissions:
  id-token: write
  contents: read

concurrency:
  group: app-workflow-${{ github.ref }}
  cancel-in-progress: true

env:
  MONGODB_VERSION: 7.0.5-jammy
  MONGODB_HOST: localhost
  MONGODB_PORT: 27017
  MONGODB_DB: doteducation
  API_PORT: 4000
  APP_PORT: 3000
  HOST: 0.0.0.0

jobs:
  app-build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.base.ref || github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.29

      - name: Set up environment variables for APP
        working-directory: packages/app
        run: |
          touch .env
          echo "NODE_ENV=test" >> .env
          echo "HOST=${{ env.HOST }}" >> .env
          echo "PORT=${{ env.APP_PORT }}" >> .env
          echo "NEXT_PUBLIC_BASE_URL=http://${{ env.HOST }}:${{ env.APP_PORT }}" >> .env
          echo "NEXT_PUBLIC_API_DOMAIN=http://${{ env.HOST }}:${{ env.API_PORT }}" >> .env

      - name: Install dependencies
        run: bun i

      - name: Format
        run: bun run format

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Set up environment variables for API
        working-directory: packages/api
        run: |
          touch .env
          echo "NODE_ENV=test" >> .env
          echo "HOST=${{ env.HOST }}" >> .env
          echo "PORT=${{ env.API_PORT }}" >> .env
          echo "MONGODB_URI=mongodb://${{ env.MONGODB_HOST }}:${{ env.MONGODB_PORT }}/${{ env.MONGODB_DB }}" >> .env

      - name: Create logs directory
        run: mkdir -p logs

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ env.MONGODB_VERSION }}
          mongodb-port: ${{ env.MONGODB_PORT }}
          mongodb-db: ${{ env.MONGODB_DB }}

      - name: Start API
        working-directory: packages/api
        run: bun dev > ../../logs/api.log 2>&1 &

      - name: Start APP
        working-directory: packages/app
        run: bun dev > ../../logs/app.log 2>&1 &

      - name: Test with Cypress
        working-directory: packages/app
        run: bun run wait && bun run test

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          include-hidden-files: true
          path: packages/app/cypress/screenshots

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: service-logs
          include-hidden-files: true
          path: logs
