name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: test
  HOST: 0.0.0.0
  APP_PORT: 3000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.29

      - name: Set up environment variables
        run: |
          touch .env
          echo "NODE_ENV=${{ env.NODE_ENV }}" >> .env
          echo "HOST=${{ env.HOST }}" >> .env
          echo "PORT=${{ env.APP_PORT }}" >> .env
          echo "NEXT_PUBLIC_BASE_URL=http://${{ env.HOST }}:${{ env.APP_PORT }}" >> .env

      - name: Install dependencies
        run: bun i

      - name: Format check
        run: bun run format

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build
